- .travis.yml
- demo/server.js
- package.json
- test/selenium.js
Still to do: move the Selenium initialization scripts in the top-directory (or create a new node package that handles that)
> Convert Selenium tests to use Mocha

- package.json
> Install 'mocha' locally

- test/tests/testEncrypt.js
- test/tests/testSendNotification.js
> Add padSize parameter to http_ece decrypt calls in tests

- package.json
> Revert http_ece to version 0.2.0

- .travis.yml
- test/selenium-init.js
- test/testSelenium.js
> Don't rely on Travis to download Firefox

- test/testSelenium.js
> If GCM_API_KEY isn't defined, at least run Selenium tests with Firefox

- README.md
> Explain how to run tests in the documentation

- .eslintrc
- package.json
- test/testSelenium.js
> Add linting

- README.md
> Update documentation about the Promise returned by sendNotification

- test/service-worker.js
https://bugs.chromium.org/p/chromium/issues/detail?id=593454 has been fixed.
> Remove Chromium hack for no-payload tests

- package.json
- test/index.html
- test/server.js
- test/testSelenium.js
- test/testSendNotification.js
Instead of assuming 50005 is available.
> Use portfinder

- package.json
- test/testSelenium.js
> Pin selenum-webdriver to version 2.52.0

- README.md
- index.js
- package.json
- test/index.html
- test/selenium-init.js
- test/server.js
- test/testEncrypt.js
- test/testEncryptOld.js
- test/testSelenium.js
- test/testSendNotification.js
Fixes #115.
Depends on https://github.com/martinthomson/encrypted-content-encoding/issues/17.
> Support push payloads with GCM

- .travis.yml
- README.md
- index.js
- test/selenium-init.js
- test/testSelenium.js
- test/testSendNotification.js
> Support VAPID when sending notifications with payload

- package.json
> Use standard http_ece package (0.4.5)

- test/testSelenium.js
> Make it possible to define VAPID keys to use during tests via env variables

- index.js
- test/testSendNotification.js
Fixes #124.
This can be merged only if https://bugzilla.mozilla.org/show_bug.cgi?id=1257405 and bug https://bugzilla.mozilla.org/show_bug.cgi?id=1257821 are uplifted to Firefox 46.
> Remove intermediate standard

- index.js
See https://github.com/martinthomson/encrypted-content-encoding/commit/a894708f431b0ecf5838ddb807d4d8137fea0436
> Convert strings to Buffers before encryption

- .travis.yml
- README.md
- test/selenium-init.js
- test/testSelenium.js
> Automatically download and execute Selenium server

- test/browser-managers/chrome-browsers.js
- test/testSelenium.js
> Define GCM and VAPID keys directly in tests.

- .travis.yml
- test/browser-managers/chrome-browsers.js
- test/browser-managers/firefox-browsers.js
- test/data/demo/index.html
- test/helpers/create-server.js
- test/testSelenium.js
+ adds adds chrome unstable to travis / tests
> Makes tests fail faster with helpful errors 

- index.js
- test/testSendNotification.js
This removes the GCM protocol use. It does leave in the Authorization header needed for the GCM API Key though.
> Moving GCM endpoint over to using web push protocol

- README.md
- index.js
- test/data/demo/index.html
- test/helpers/create-server.js
- test/testSelenium.js
- test/testSendNotification.js
@marco-c any chance of a review?
> Moving Chrome to using VAPID

- index.js
- test/testSetGCMAPIKey.js
> Add basic sanity checks for the GCM API key.

- package.json
- test/helpers/download-test-browsers.js
- test/testSelenium.js
This should add Firefox 49 + tests back on Travis.
> Bring the tests back to life

- .eslintrc
- bin/web-push.js
> Reintroduce bin/web-push.js

- src/vapid-helper.js
- src/web-push-lib.js
- test/test-set-vapid-details.js
- test/test-vapid-helper.js
- test/testSelenium.js
Fixes #210 and adds some tests to setVapidDetails().
> Changing vapid input / output to be base64url encoded string

- package.json
> Update repo path in package.json

- package.json
https://github.com/martinthomson/encrypted-content-encoding/pull/25 was merged and `http_ece` 0.5.2 released.
This brings down our installation size to 965.5 kB from 1.5 MB, helping a lot with #207.
```
└─┬ web-push@3.0.0 
├─┬ asn1.js@4.8.1 
│ ├── bn.js@4.11.6 
│ ├── inherits@2.0.3 
│ └── minimalistic-assert@1.0.0 
├── http_ece@0.5.2 
├─┬ jws@3.1.3 
│ ├─┬ base64url@1.0.6 
│ │ ├─┬ concat-stream@1.4.10 
│ │ │ ├─┬ readable-stream@1.1.14 
│ │ │ │ ├── core-util-is@1.0.2 
│ │ │ │ ├── isarray@0.0.1 
│ │ │ │ └── string_decoder@0.10.31 
│ │ │ └── typedarray@0.0.6 
│ │ └─┬ meow@2.0.0 
│ │   ├─┬ camelcase-keys@1.0.0 
│ │   │ ├── camelcase@1.2.1 
│ │   │ └── map-obj@1.0.1 
│ │   ├─┬ indent-string@1.2.2 
│ │   │ ├── get-stdin@4.0.1 
│ │   │ └─┬ repeating@1.1.3 
│ │   │   └─┬ is-finite@1.0.2 
│ │   │ …
```
> Update http_ece dependency

- src/web-push-lib.js
> Remove unneeded keyid parameter.

- .eslintrc
@gauntface do you mind if we remove this rule? I don't like being forced to a maximum of 80 characters sometimes at the expense of readability.
> Set max-len to 120 characters

- README.md
- src/index.js
- src/web-push-lib.js
- test/test-generate-request-details.js
- test/test-vapid-helper.js
> Request details

- src/web-push-lib.js
- test/test-generate-request-details.js
- test/testSendNotification.js
Fix #235 
@marco-c or @gauntface do you mind to take a look at my patch, please?
> Adding headers key to options for supporting future headers.

- src/web-push-error.js
- src/web-push-lib.js
Fix issue [#250](https://github.com/web-push-libs/web-push/issues/250)
> Add endpoint property in WebPushError #250

- src/vapid-helper.js
> VAPID Expiration within 12 Hours

- README.md
Update README for Samsung Internet 5.0 which is based off Chrome M51.
> Add Samsung 5.0 to Readme

- src/web-push-lib.js
At the moment the error message shows up as undefined (see here for screenshot: https://github.com/web-push-libs/web-push/issues/237#issuecomment-277581487)
> GCM Error no longer undefined

- README.md
Noticed the table wasn't working on the readme.
> Fix support table

- test/helpers/download-test-browsers.js
Fixes #293 
Retries on browser downloads.
> Adding browser download retries

- src/web-push-lib.js
- test/testSendNotification.js
> Accept any 20* response status as successful

- package-lock.json
- package.json
Until we update to the latest version, which requires more work.
> Pin http_ece to 0.7.2

- package-lock.json
- package.json
`FirefoxNightly.app` changed to `Firefox Nightly.app`
> Bumping selenium with latest firefox version support

- README.md
Added description where to put proxy if needed.
> Add proxy option to documentation

- README.md
Fixes #332.
@aliams could you review too?
> Update documentation about support for Edge

- src/cli.js
patch suggestion for issue #358
> fix encoding argument in cli

- src/web-push-lib.js
- test/test-generate-request-details.js
> Make aes128gcm the default content encoding

- package-lock.json
- package.json
- src/cli.js
- src/encryption-helper.js
- src/vapid-helper.js
- src/web-push-lib.js
- test/test-generate-request-details.js
- test/test-vapid-helper.js
- test/testSelenium.js
- test/testSendNotification.js
* Update eslint-config-airbnb to v17
* Fix resulting linting errors
Fixes #405.
> Update eslint-config-airbnb to v17

- README.md
- src/web-push-lib.js
- test/test-generate-request-details.js
> Allow proxy options object as a proxy parameter

- .travis.yml
- package-lock.json
- package.json
> Upload coverage to coveralls

- .gitignore
- src/vapid-helper.js
- test/test-vapid-helper.js
Ref: #656
Hello, this PR fixed incorrect validation of VAPID keys, but it's a breaking change.
> fix!: correct validation of VAPID keys
