web-push-libs/web-push

index.js, test/tests/testSendNotification.js
GCM uses the Retry-After header during outages - http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.37
=> Include response headers too

README.md
Firefox 44 is the first version that supports the Push API.
=> Update README.md to match the first supported Firefox version

index.js
=> Use standard base64 in the raw_data field of the GCM payload

index.js, package.json, test/testSendNotification.js
Fixes #120.
Depends on https://github.com/martinthomson/encrypted-content-encoding/pull/18.
=> Support new encryption standards for newer Firefox versions

.travis.yml, README.md, package.json, test/server.js, test/testSelenium.js
Fixes #111.
`profilePath_` won't be available anymore (https://github.com/SeleniumHQ/selenium/issues/1827), so we have to remove the tests involving a restart of the browser.
It isn't a huge problem, since those tests didn't have a clear value and were hard to maintain.
=> Update selenium webdriver

bin/web-push.js, package.json
vapid and userAuth parameters configurable.
For using vapi add parameter --vapid.
For adding userAuth add parameter --auth=<your auth>
Example:
```bash
web-push --endpoint=https://updates.push.services.mozilla.com/push/v1/gAAAAABW8oWpBwhTzvvSxB-OKwsETosMvOsV75xUGLOQKXckw__twjoNHMIc-OkDljcs2aUaimxjhWUgZRcNZomdzdsgxXlW4dMpCiLzKa72JsQoEfBygiCHlmxxHlPJlimmzFSuk7eP --key=" BHwue1TPjc0sL4tnNway5HnW6qdD9Efi8AgUNyOw0CdUcNe2EvssLlqG8mK6Btc0t3KW9OCgSdJ6RQD6cpouzkY=" --payload="{\"body\":\"Molo mucho\"}"
```
=> Adds command line executable

.travis.yml, README.md, index.js, package.json, shim.js, test/testSelenium.js
Depends on https://github.com/martinthomson/encrypted-content-encoding/pull/21 to be merged and published to actually work on node 0.10. We will maybe have to bump the http_ece module version in package.json before merging this, depending on the new version number.
I had to use a version of selenium-webdriver that was supported by both Node 0.10 and Node 4.
Sadly it only works with the selenium-server between the browser and the node process.
I don't mind skipping the selenium tests for 0.10 by adding another exception [here](https://github.com/marco-c/web-push/blob/707075d4e20316bea579dc66f7afa230d931e93d/test/testSelenium.js#L28) (but they did help me catch a bug though).
=> Add support for Node 0.10

test/testSelenium.js
Selenium tests didn't work with Aurora 47, now they don't work with Beta 47.
=> Disable Selenium tests with Firefox Beta

bin/web-push.js
Fixes #168 - the variable names were never actually declared so private keys and public keys from the command line would never be used.
=> Fixes issue where getKeys would always return new VAPID keys

package.json, test/testSelenium.js
This makes tests retry up to 3 times before being classed as failed - this is handy given the selenium tests can fail from time to time. Should make Travis more reliable. Also updated selenium-assistant to work with the latest changes to geckodriver release.
=> Offer retries in tests and update selenium-assistant

index.js, test/testSendNotification.js
=> Allow overriding GCM API key with a sendNotification argument.

.npmignore
This will save a few bytes and will help me remember not to package the `wires` executable.
=> Add more files to .npmignore

.gitignore, README.md, bin/web-push.js, package.json, src/cli.js, src/vapid-helper.js, test/test-cli.js
Implements comments from: #213
@marco-c
=> Cli update

src/index.js
This can be helpful in identifying errors, such as `err instanceof WebPushError`, etc. For your consideration!
=> Expose WebPushError as a public API

src/web-push-lib.js
Library was returning incorrect endpoint if webpush.sendNotification(....) was called in a loop.
=> Returned correct push endpoint in case of error.

src/web-push-lib.js
Google says in their developer pages
> This is the origin of the push service (NOT the origin of your site). In JavaScript, you could do the following to get the audience: const audience = new URL(subscription.endpoint).origin
[Source](https://developers.google.com/web/updates/2016/07/web-push-interop-wins#sending_a_push_message)
W3C says (at least in W3CSchools)
> Return the protocol, hostname and port number of a URL.
[Source](http://www.w3schools.com/jsref/prop_loc_origin.asp)
I guess, the old line would cause problems, if a browser vendor decided to run their endpoint service somewhere else than port 80 or 443.
=> Replaced hostname with host

src/vapid-helper.js, test/test-vapid-helper.js
This PR let's the people add Custom Expiration to their vapid headers, but it seems expiration is a completed part and this is just the initial PR, the validation of the expiration can be more complex too.
The `validateExpiration` does not check the time for the minimum since minimums can be different in all points of time.
I have added a basic test suite of valid and invalid expiration examples, following the pattern in `test-vapid-helpers.js`, if  there are updates to be made, please himmeup with a comment.
Date.now() returns time in UTC since UNIX Epoch as we all know. Are we guaranteed the push service is going to parse this in the UTC and not other timezone? The expiry parsing on the Push Service shouldn't be dependent on the timezone of the Server?
UPDATE: It's guaranteed to be …
=> Add option to add Custom Expiration

test/test-generate-request-details.js
Integration test for Endpoint passed to Audience in Vapid. This uses jws to decode the Authorization header returned with the value and tests if it contains the expected audience.
This is a test to accompany the change in #267 and resolves #270.
=> Add Test For Port Number passed to Audience in Vapid

.travis.yml
I don't know why we were manually installing it since it is in package.json. Since this manual installation makes builds fail with the latest version of Node, let's avoid it.
=> Don't manually install mocha

README.md, test/test-cli.js
I already added the support for CLI in the previous PR, but I didn't update the docs and test. This PR updates the docs and the test.
=> Add aes128gcm support for CLI

README.md
Escaping non-special characters in regular expressions doesn’t have any effect.
=> Remove useless escape

src/web-push-lib.js
Remove the FCM endpoint modification for AES_128_GCM content encoding
=> fcm/send/ endpoint supports AES_128_GCM

src/web-push-lib.js, test/testSendNotification.js
Closes #445 
I added some tests for multiple FCM cases, but I had to fix the vapid validation for that. Please review those changes once.
Also should I separate the tests for FCM from current GCM tests?
=> Allow falsy values for vapidDetails

README.md, src/web-push-lib.js, test/test-generate-request-details.js
Hello!
I'am using web-push to send a lot of push-notifications. We have got more than 3000rps.
To make sender service faster, i'am now doing something like this:
```
webPush.setVapidDetails(
'mailto:help@test.com',
config.vapid_public_key,
config.vapid_private_key
);
https.globalAgent = new https.Agent({
keepAlive: true,
keepAliveMsecs: 100,
...
});
```
But it is not convenient to rewrite global agent.
Cause of this reason i have added `agent` options to specify a `https.Agent` instance
=> Add https.agent options

src/web-push-lib.js
`https-proxy-agent` patches core Node methods in `https` for whatever reason, and that breaks unrelated code. In our app we don't use proxy, and the mere fact that `web-push` requires the proxy package, it breaks other code.
See https://github.com/TooTallNate/node-agent-base/issues/35 and https://github.com/sindresorhus/got/issues/951
=> Require https-proxy-agent only when actually needed

package-lock.json, src/vapid-helper.js
Trailing zeroes lead to invalid JWT tokens in FCM and invalid authorization in Mozilla Push, leading zeroes are skipped and succeed
=> Fix issue #532, pad keys with leading zeroes instead of trailing zeroes

src/web-push-lib.js
There are two checks for the same subscription object. I added one extra check for the first condition and remove second one.
=> remove useless seconds subscription.keys validation

README.md, src/vapid-helper.js, src/web-push-lib.js
There's some areas in code which are redundant. Plus readme indicates that `aesgcm` is the default but in fact it's `aes128gcm`.
=> skip redundant code code, correct readme

README.md, src/web-push-constants.js, src/web-push-lib.js, test/test-generate-request-details.js
Adding support for web push notifications for Safari 16.
- Web push notifications support including topic and urgency headers.
- Updated readme file.
I'm working on a project that implements web push notifications using the web-push npm package. I've realized that Safari support didn't make it to the package yet, so I made this PR to add support for Safari. I was hesitant to open a PR before having a discussion with the community/team, but I think the modifications are simple enough to have that discussion on the PR. This is my first OSS PR, would love some feedback.
=> Add support for Urgency and Topic optional parameters

src/web-push-lib.js
Support for the 'Topic' optional parameter was introduced in PR #764 but it is not functioning due to incorrect capitalization.
As a newcomer to open-source contributions, I apologize if my approach seems impolite. Thank you.
=> Fix options from 'Topic' to 'topic'

README.md, src/vapid-helper.js
I built a sample project today for my colleagues that uses web-push, and noticed that the `setVapidDetails()` method isn't documented, so I added that.
In addition, during the building of my project, I noticed that everything worked fine until I got to Safari, which rejected attempts to send a new push notification to a subscriber endpoint with a `BadJwtToken` error. Debugging it, I found that Apple's push notification endpoint used by Safari (at least Safari v16.4 on macOS) appears to not allow `https://localhost` URIs as VAPID subjects; changing my VAPID subject to either a `mailto:` URI or any `https:` URI that wasn't `localhost` allowed Safari to succeed, but using `https://localhost` (in any way at all, e.g., with or without port numbers) reverted back to the push notification …
=> add documentation for setVapidDetails method

src/web-push-lib.js, test/testSendNotification.js
https-proxy-agent 7.x changed the default export
https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/README.md#https-module-example
=> fix(sendnotification): fix HttpsProxyAgent error

src/index.js, test/test-generate-request-details.js, test/test-set-vapid-details.js, test/testSendNotification.js, test/testSetGCMAPIKey.js
Fixes #683
I was able to reproduce the TypeScript issue seen in #683 within the existing test suite in 30c5932.  Previously, requiring `sendNotification` as a named import would fail [here](https://github.com/web-push-libs/web-push/blob/master/src/web-push-lib.js#L341) due to the function lacking reference to the prototype instance.  5277eea binds the prototype instance to the exported `sendNotification` function using [ES5 syntax](https://caniuse.com/es5).  The pattern of testing on named imports is extended to all other `WebPushLib` methods in 2548c3a to prevent the same issue from occurring on another method in the future.
=> Fixes sendNotification named import declaration

src/vapid-helper.js
Fixes #830
Fix the "https: or mailto:" error being overwritten by the error in the catch by passing it upwards trough the cause property
=> Fix validation error of protocol not beeing returned

.gitignore
`npm test` generates a `.nyc_output` directory that shouldn't be committed to the repository.
=> adds .nyc_output/ to .gitignore

README.md
According to https://github.com/mdn/serviceworker-cookbook/pull/335,  "The domain https://serviceworke.rs/ (do not open) has been overtaken and are used to steal clicks. This removes the domain and uses a dummy domain."
=> Remove link to serviceworke.rs
